import { CommissionInterface } from "@/types/commission";

export const dummyCommission: CommissionInterface[] = [
  {
    commissionID: "comm12345",
    onBoardingClientID: "client001",
    commissionName: "Ernest Mwinchumu",
    commissionAmount: 500.0,
    commissionDate: "2024-09-01",
    commissionType: "Internal Referral",
    commissionStatus: "Issued",
    commissionPaymentMethod: "Commission Split",
    commissionPaymentFigure: 10,
    commissionNote: "Commission for September sales",
    createdAt: "2024-09-02T12:00:00Z",
    updatedAt: "2024-09-05T15:00:00Z",
    OnBoardingClient: [
      {
        vfdLetterStatus: "Sent",
        efdmsStatus: "Complete",
        paymentStatus: "Completed",
        onboardingStatus: "Finished",
        loginCredentials: "client001@domain.com",
        address: "123 Business Street",
        businessCategory: "Retail",
        certificatePassword: "certPass123",
        companyName: "Business A",
        emailUsedForComms: "info@businessA.com",
        emailUsedForLogin: "login@businessA.com",
        fullName: "John Doe",
        phoneNumber: "255712345678",
        platform: "Simplify",
        service: "VFD",
        tin: "123456789",
        vrn: "987654321",
        serialNumber: "SER12345",
        onBoardingClientID: "client001",
        stage: "Final",
        amountPaid: 1000.0,
        proofOfPaymentText: "Issued via bank transfer",
        createdAt: "2024-08-01T09:00:00Z",
        updatedAt: "2024-08-15T12:00:00Z",
        isVip: false,
        leadID: 1001,
        documentLink: "https://example.com/documents/client001",
        specificPlatform: "Standard",
      },
    ],
  },
  {
    commissionID: "comm12346",
    onBoardingClientID: "client002",
    commissionName: "Nora",
    commissionAmount: 300.0,
    commissionDate: "2024-09-03",
    commissionType: "Internal Referral",
    commissionStatus: "Not Issued",
    commissionPaymentMethod: "",
    commissionPaymentFigure: null,
    commissionNote: "Referral for new client sign-up",
    createdAt: "2024-09-04T10:00:00Z",
    updatedAt: "2024-09-06T12:30:00Z",
    OnBoardingClient: [
      {
        vfdLetterStatus: "Pending",
        efdmsStatus: "Pending",
        paymentStatus: "Incomplete",
        onboardingStatus: "In Progress",
        loginCredentials: null,
        address: "456 Corporate Avenue",
        businessCategory: "Manufacturing",
        certificatePassword: "certPass789",
        companyName: "Business B",
        emailUsedForComms: "contact@businessB.com",
        emailUsedForLogin: null,
        fullName: "Jane Smith",
        phoneNumber: "255713456789",
        platform: "Simplify",
        service: "EFDMS",
        tin: "223344556",
        vrn: "556677889",
        serialNumber: "SER54321",
        onBoardingClientID: "client002",
        stage: "Onboarding",
        amountPaid: 500.0,
        proofOfPaymentText: "Issued via mobile money",
        createdAt: "2024-08-10T10:30:00Z",
        updatedAt: "2024-08-20T14:00:00Z",
        isVip: true,
        leadID: 1002,
        documentLink: "https://example.com/documents/client002",
        specificPlatform: "Premium",
      },
    ],
  },
  {
    commissionID: "comm12347",
    onBoardingClientID: "client003",
    commissionName: "Kija",
    commissionAmount: 700.0,
    commissionDate: "2024-09-05",
    commissionType: "External Referral",
    commissionStatus: "Issued",
    commissionPaymentMethod: "Commission Split",
    commissionPaymentFigure: 10,
    commissionNote: null,
    createdAt: "2024-09-06T11:00:00Z",
    updatedAt: "2024-09-08T13:00:00Z",
    OnBoardingClient: [
      {
        vfdLetterStatus: "Sent",
        efdmsStatus: "Complete",
        paymentStatus: "Completed",
        onboardingStatus: "Finished",
        loginCredentials: "client003@domain.com",
        address: "789 Tech Road",
        businessCategory: "Technology",
        certificatePassword: "techPass456",
        companyName: "Business C",
        emailUsedForComms: "admin@businessC.com",
        emailUsedForLogin: "login@businessC.com",
        fullName: "Michael Brown",
        phoneNumber: "255714567890",
        platform: "Simplify",
        service: "VFD",
        tin: "334455667",
        vrn: "667788990",
        serialNumber: "SER67890",
        onBoardingClientID: "client003",
        stage: "Complete",
        amountPaid: 1500.0,
        proofOfPaymentText: "Issued via credit card",
        createdAt: "2024-08-05T12:00:00Z",
        updatedAt: "2024-08-18T15:30:00Z",
        isVip: false,
        leadID: 1003,
        documentLink: "https://example.com/documents/client003",
        specificPlatform: "Standard",
      },
    ],
  },
  {
    commissionID: "comm12348",
    onBoardingClientID: "client004",
    commissionName: "Sales Commission",
    commissionAmount: 800.0,
    commissionDate: "2024-09-07",
    commissionType: "Client Referral",
    commissionStatus: "Issued",
    commissionPaymentMethod: "Subscription Reduction",
    commissionPaymentFigure: 5,
    commissionNote: "Bonus for exceeding targets",
    createdAt: "2024-09-08T12:00:00Z",
    updatedAt: "2024-09-09T16:00:00Z",
    OnBoardingClient: [
      {
        vfdLetterStatus: "Sent",
        efdmsStatus: "Complete",
        paymentStatus: "Completed",
        onboardingStatus: "Finished",
        loginCredentials: "client004@domain.com",
        address: "1012 Logistics Blvd",
        businessCategory: "Logistics",
        certificatePassword: "logPass321",
        companyName: "Business D",
        emailUsedForComms: "logistics@businessD.com",
        emailUsedForLogin: "login@businessD.com",
        fullName: "Emma White",
        phoneNumber: "255715678901",
        platform: "Simplify",
        service: "VFD",
        tin: "445566778",
        vrn: "778899001",
        serialNumber: "SER98765",
        onBoardingClientID: "client004",
        stage: "Final",
        amountPaid: 2000.0,
        proofOfPaymentText: "Issued via bank transfer",
        createdAt: "2024-08-12T09:00:00Z",
        updatedAt: "2024-08-25T14:00:00Z",
        isVip: true,
        leadID: 1004,
        documentLink: "https://example.com/documents/client004",
        specificPlatform: "Premium",
      },
    ],
  },
];